/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'memes' : IDL.Null,
  'food' : IDL.Null,
  'misc' : IDL.Null,
  'animals' : IDL.Null,
  'emotions' : IDL.Null,
  'reactions' : IDL.Null,
});
export const Time = IDL.Int;
export const Sticker = IDL.Record({
  'id' : IDL.Nat32,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'createdAt' : Time,
  'tags' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
  'viewCount' : IDL.Nat,
  'category' : Category,
});

export const idlService = IDL.Service({
  'addSticker' : IDL.Func(
      [IDL.Text, IDL.Text, Category, IDL.Vec(IDL.Text)],
      [IDL.Nat32],
      [],
    ),
  'getAllStickers' : IDL.Func([], [IDL.Vec(Sticker)], ['query']),
  'getSticker' : IDL.Func([IDL.Nat32], [Sticker], ['query']),
  'getStickersByCategory' : IDL.Func([Category], [IDL.Vec(Sticker)], ['query']),
  'getStickersByLikes' : IDL.Func([], [IDL.Vec(Sticker)], ['query']),
  'getStickersByViews' : IDL.Func([], [IDL.Vec(Sticker)], ['query']),
  'incrementLikeCount' : IDL.Func([IDL.Nat32], [], []),
  'incrementViewCount' : IDL.Func([IDL.Nat32], [], []),
  'initialize' : IDL.Func([], [], []),
  'searchStickers' : IDL.Func([IDL.Text], [IDL.Vec(Sticker)], ['query']),
  'seedStickers' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'memes' : IDL.Null,
    'food' : IDL.Null,
    'misc' : IDL.Null,
    'animals' : IDL.Null,
    'emotions' : IDL.Null,
    'reactions' : IDL.Null,
  });
  const Time = IDL.Int;
  const Sticker = IDL.Record({
    'id' : IDL.Nat32,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'createdAt' : Time,
    'tags' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
    'viewCount' : IDL.Nat,
    'category' : Category,
  });
  
  return IDL.Service({
    'addSticker' : IDL.Func(
        [IDL.Text, IDL.Text, Category, IDL.Vec(IDL.Text)],
        [IDL.Nat32],
        [],
      ),
    'getAllStickers' : IDL.Func([], [IDL.Vec(Sticker)], ['query']),
    'getSticker' : IDL.Func([IDL.Nat32], [Sticker], ['query']),
    'getStickersByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Sticker)],
        ['query'],
      ),
    'getStickersByLikes' : IDL.Func([], [IDL.Vec(Sticker)], ['query']),
    'getStickersByViews' : IDL.Func([], [IDL.Vec(Sticker)], ['query']),
    'incrementLikeCount' : IDL.Func([IDL.Nat32], [], []),
    'incrementViewCount' : IDL.Func([IDL.Nat32], [], []),
    'initialize' : IDL.Func([], [], []),
    'searchStickers' : IDL.Func([IDL.Text], [IDL.Vec(Sticker)], ['query']),
    'seedStickers' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };