/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'memes' : null } |
  { 'food' : null } |
  { 'misc' : null } |
  { 'animals' : null } |
  { 'emotions' : null } |
  { 'reactions' : null };
export interface Sticker {
  'id' : number,
  'title' : string,
  'likeCount' : bigint,
  'createdAt' : Time,
  'tags' : Array<string>,
  'imageUrl' : string,
  'viewCount' : bigint,
  'category' : Category,
}
export type Time = bigint;
export interface _SERVICE {
  'addSticker' : ActorMethod<[string, string, Category, Array<string>], number>,
  'getAllStickers' : ActorMethod<[], Array<Sticker>>,
  'getSticker' : ActorMethod<[number], Sticker>,
  'getStickersByCategory' : ActorMethod<[Category], Array<Sticker>>,
  'getStickersByLikes' : ActorMethod<[], Array<Sticker>>,
  'getStickersByViews' : ActorMethod<[], Array<Sticker>>,
  'incrementLikeCount' : ActorMethod<[number], undefined>,
  'incrementViewCount' : ActorMethod<[number], undefined>,
  'initialize' : ActorMethod<[], undefined>,
  'searchStickers' : ActorMethod<[string], Array<Sticker>>,
  'seedStickers' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];